sudo: required

services:
  - docker

before_install:
- docker-compose pull
- docker-compose build
- docker-compose up -d db
- docker-compose run app gom init
- docker-compose run app gom migrate

script:
- docker-compose run app go test ./...