version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://easyalert:easyalert@db/easyalert_development?sslmode=disable
      PORT: 8000
      GO111MODULE: "on"
      RUNNER_ROOT: "/go/src/github.com/bakku/easyalert"
      RUNNER_TMP_PATH: "/tmp"
    volumes:
      - "/go/src/github.com/bakku/easyalert/build/"
      - ".:/go/src/github.com/bakku/easyalert"
    links:
      - db
    command: air -c /go/src/github.com/bakku/easyalert/cmd/easyalert/air.conf
  db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: easyalert
      POSTGRES_PASSWORD: easyalert
      DEV_DB: easyalert_development
      TEST_DB: easyalert_test
    ports:
      - 5432:5432
    volumes:
      - "./docker/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh"
