version: '3'
volumes:
  vendor:
  build:
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://easyalert:easyalert@db/easyalert_development?sslmode=disable
      PORT: 8000
    volumes:
      - ".:/go/src/github.com/bakku/easyalert"
      - "vendor:/go/src/github.com/bakku/easyalert/vendor"
      - "build:/go/src/github.com/bakku/easyalert/build"
    links:
      - db
  db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: easyalert
      POSTGRES_PASSWORD: easyalert
      DEV_DB: easyalert_development
      TEST_DB: easyalert_test
    ports:
      - 5432:5432
    volumes:
      - "./docker/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh"
